'use strict';
const D=window.DEMO_DATA, $=id=>document.getElementById(id);
let imageIndex=0,loadedImage=null,renderVersion=0;
function unpack(s){const bytes=atob(s),out=new Uint8Array(160*160);for(let i=0;i<out.length;i++)out[i]=(bytes.charCodeAt(i>>3)>>(7-(i&7)))&1;return out;}
function option(value,label){const e=document.createElement('option');e.value=value;e.textContent=label;return e;}
for(const select of ['leftModel','rightModel','liveModel'])for(const job of D.jobs)$(select).append(option(job,D.names[job]));
$('leftModel').value='M0_seed0';$('rightModel').value='M2_seed0';$('liveModel').value='M2_seed0';
$('caseSelect').append(option('','전체 목록에서 직접 선택'));
D.cases.forEach((c,i)=>$('caseSelect').append(option(i,c.title)));
D.images.forEach((im,i)=>$('imageSelect').append(option(i,`${String(i).padStart(3,'0')} · ${im.source.split('/').pop()}`)));
function region(gt){let x0=159,y0=159,x1=0,y1=0;for(let y=0;y<160;y++)for(let x=0;x<160;x++)if(gt[y*160+x]){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}if(x1<x0)return [0,0,640,640];let size=Math.min(640,Math.max(160,Math.max(x1-x0,y1-y0)*4+96)),cx=(x0+x1)*2,cy=(y0+y1)*2;return [Math.max(0,Math.min(640-size,cx-size/2)),Math.max(0,Math.min(640-size,cy-size/2)),size,size];}
function paint(canvas,image,predBits,gtBits,mode='difference',zoom=false){const temp=document.createElement('canvas');temp.width=temp.height=640;const ctx=temp.getContext('2d');ctx.drawImage(image,0,0,640,640);const p=unpack(predBits),g=gtBits?unpack(gtBits):new Uint8Array(25600);if(mode!=='plain'){const layer=document.createElement('canvas');layer.width=layer.height=160;const l=layer.getContext('2d'),pix=l.createImageData(160,160);for(let i=0;i<25600;i++){let c=null;if(mode==='difference'&&gtBits)c=p[i]&&g[i]?[66,190,128]:g[i]?[255,173,66]:p[i]?[239,102,157]:null;else if(p[i])c=[57,174,240];if(mode==='overlay'&&g[i]){const x=i%160,y=Math.floor(i/160);if(!x||!y||x===159||y===159||!g[i-1]||!g[i+1]||!g[i-160]||!g[i+160])c=[66,230,128];}if(c){pix.data.set(c,i*4);pix.data[i*4+3]=mode==='overlay'?130:155;}}l.putImageData(pix,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(layer,0,0,640,640);}const display=canvas.getContext('2d');display.clearRect(0,0,640,640);if(zoom&&gtBits)display.drawImage(temp,...region(g),0,0,640,640);else display.drawImage(temp,0,0);}
async function render(){const version=++renderVersion,im=D.images[imageIndex];const image=new Image();image.src=im.image;await image.decode();if(version!==renderVersion)return;loadedImage=image;for(const side of ['left','right']){const job=$(side+'Model').value,r=D.predictions[job][imageIndex];paint($(side),image,r.mask_bits,im.gt_bits,$('mode').value,$('zoom').value==='target');$(side+'Stats').textContent=`Union IoU ${r.union_iou.toFixed(3)} · 객체 TP ${r.tp} / FP ${r.fp} / FN ${r.fn} · 예측 ${r.n_pred}개`;}}
function selectCase(i){const c=D.cases[i];imageIndex=c.index;$('imageSelect').value=imageIndex;$('leftModel').value=c.left;$('rightModel').value=c.right;$('reason').textContent=c.reason;render();}
$('caseSelect').onchange=()=>{if($('caseSelect').value!=='')selectCase(Number($('caseSelect').value));};
$('imageSelect').onchange=()=>{imageIndex=Number($('imageSelect').value);$('caseSelect').value='';$('reason').textContent='전체 Test에서 직접 선택한 이미지입니다. 추천 사례 선정과 무관하게 모든 모델의 예측을 비교할 수 있습니다.';render();};
for(const id of ['leftModel','rightModel','mode','zoom'])$(id).onchange=render;
function save(id,name){const a=document.createElement('a');a.download=name;a.href=$(id).toDataURL('image/png');a.click();}
$('saveLeft').onclick=()=>save('left',`case_${imageIndex}_${$('leftModel').value}.png`);$('saveRight').onclick=()=>save('right',`case_${imageIndex}_${$('rightModel').value}.png`);$('saveLive').onclick=()=>save('live','live_prediction.png');
$('runLive').disabled=true;
if(location.protocol==='file:')$('liveStatus').textContent='오프라인 사례 재생 모드입니다. 새 이미지 추론은 DEMO_GUIDE_KO.md의 서버 실행 안내를 따르세요.';
else fetch('/api/health').then(r=>{if(!r.ok)throw Error();return r.json();}).then(()=>{$('runLive').disabled=false;$('liveStatus').textContent='GPU 추론 서버에 연결됐습니다. 모델 첫 호출에는 로딩 시간이 추가됩니다.';}).catch(()=>{$('liveStatus').textContent='추론 서버가 연결되지 않았습니다. 저장된 사례 비교는 사용할 수 있습니다.';});
$('runLive').onclick=async()=>{const file=$('upload').files[0];if(!file){$('liveStatus').textContent='이미지를 선택하세요.';return;}$('runLive').disabled=true;$('liveStatus').textContent='실제 모델 추론 중입니다…';try{const image=await new Promise((ok,fail)=>{const f=new FileReader();f.onload=()=>ok(f.result);f.onerror=fail;f.readAsDataURL(file);});const response=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job:$('liveModel').value,image})});const r=await response.json();if(!response.ok)throw Error(r.error);const img=new Image();img.src=r.image;await img.decode();paint($('live'),img,r.mask_bits,null,'overlay',false);$('liveStatus').textContent=`${D.names[r.job]} · 예측 ${r.n_pred}개 · forward+후처리 ${r.inference_ms.toFixed(1)}ms · 서버 처리 ${r.server_ms.toFixed(1)}ms${r.cold_model_load?' (모델 로딩/워밍업 포함)':''}\n정답 없는 새 이미지: 정확도/IoU는 계산하지 않습니다.`;}catch(e){$('liveStatus').textContent='추론 실패: '+e.message;}finally{$('runLive').disabled=false;}};
$('caseSelect').value='0';selectCase(0);
